name: farmer_counter
description: "Simple counter that helps farmers count things"
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  collection: 1.19.1
  connectivity_plus: 6.1.5
  crypto: 3.0.6
  cupertino_icons: 1.0.8
  easy_localization: 3.0.8
  easy_logger: 0.0.2
  extension_google_sign_in_as_googleapis_auth: 3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  freezed_annotation: 3.1.0
  flutter_hooks: 0.21.3+1
  fl_chart: 1.0.0
  http: 1.5.0
  hooked_bloc: 1.7.0
  hydrated_bloc: 10.1.1
  intl: 0.20.2
  isar_community: 3.2.0-dev.2
  isar_community_flutter_libs: 3.2.0-dev.2
  json_annotation: 4.9.0
  get_it: 8.2.0
  googleapis: 14.0.0
  google_sign_in: 7.1.1
  path: 1.9.1
  path_provider: 2.1.5
  provider: 6.1.5+1
  uuid: 4.5.1
  shared_preferences: 2.5.3

dev_dependencies:
  bloc_test: 10.0.0
  build_runner: 2.5.0
  freezed: 3.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  isar_community_generator: 3.2.0-dev.2
  json_serializable: 6.9.4
  mocktail: 1.0.4
  flutter_launcher_icons: 0.14.4
flutter_icons:
    android: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/